// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://udtgwhnmqwbkshrvsxtp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVkdGd3aG5tcXdia3NocnZzeHRwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODc4MDg5OTksImV4cCI6MjEwMzM4NDk5OX0.ekxqukbNbCVTl0-ZRVurYIOsVlbzHUuwKieQUm6Gzz0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== 'undefined' ? localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
  }
});